name: 1. Usina Longos (ES)

on:
  schedule:
    - cron: '23 5 * * *' # 02:23 BRT
    - cron: '23 7 * * *' # 04:23 BRT
    - cron: '23 9 * * *' # 06:23 BRT
  workflow_dispatch: 

jobs:
  produzir_videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3' # Atualizado para evitar DeprecationWarning
      - run: pip install google-genai gspread
      - env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python usina.py
